kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-volumeclaim
spec:
  selector:
    matchLabels:
      type: nfs-mysql-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi 