kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wp-pvc
spec:
  selector:
    matchLabels:
      type: nfs-wp-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi 