apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: wordpress
          name: wordpress
          env:
          - name: WORDPRESS_DB_HOST
            value: mysql:3306
          - name: WORDPRESS_DB_NAME
            # value: mydb
            valueFrom:
                configMapKeyRef:
                  key: mysql_database
                  name: mysql-config
          - name: WORDPRESS_DB_USER
            # value: myuser
            valueFrom:
                configMapKeyRef:
                  key: mysql_user
                  name: mysql-config
          - name: WORDPRESS_DB_PASSWORD
            # value: userpass
            valueFrom:
                secretKeyRef:
                  key: user_pw
                  name: mysql-secret
          ports:
            - containerPort: 80
              name: wordpress
          resources:
            requests:
              memory: "1024Mi"
              cpu: "800m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pvc