Vagrant.configure("2") do |config|
        # docker_server for nfs-storage
        config.vm.define "storage-srv" do |cfg|
                cfg.vm.box = "generic/centos7"
                cfg.vm.provider "virtualbox" do |vb|
                        vb.name = "storage-srv"
                        vb.cpus = 2
                        vb.memory = 2048
			vb.gui = true
                end
                cfg.vm.host_name = "storage.example.com"
                cfg.vm.network "private_network", ip: "192.168.93.99"
                cfg.vm.provision "shell", path: "ssh_conf.sh", privileged: true
                cfg.vm.provision "shell", path: "nfs_conf.sh", privileged: true
        end
end
