apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
    - name: redis
      image: redis
      volumeMounts:
        - name: redis-storage
          mountPath: /data/redis
  volumes:
    # 기본값
    - name: redis-storage
      emptyDir: {}
      
    # 메모리사용
    # tmpfs                              2.0G     0  2.0G   0% /data/redis
    # - name: redis-storage
    #   emptyDir:
    #     medium: Memory
    #     sizeLimit: 2Gi