# 아래와 같이 nfs 설정을 해놓은 상태임
# 192.168.31.100:/var/nfs_storage     62G  5.2G   54G   9% /mnt/nfs_storage
apiVersion: apps/v1
kind: ReplicaSet # 파드를 만듬
metadata:
  name: apahce-pod-replica # 파드의 이름
  # labels:
  #   app: apahce-replica
spec:
  replicas: 10 # 0 으로 변경하여 삭제
  selector:
    matchLabels:
      app: apahce-replica # template.metadata.labels.[key] 와 맞아야함.
  # 어떤 형태로 만들 것인가.
  template:
    metadata:
      labels:
        app: apahce-replica # selector.matchLabels.[key] 와 맞아야함.
    spec:
      containers:
        - name: ac
          image: httpd:2.4
          ports:
            - containerPort: 80
          volumeMounts:
          - mountPath: /usr/local/apache2/htdocs
            name: nfs-volume # 일치해야함
            # 당연히 container 안에서 수정 안됨
            # bash: index.html: Read-only file system
            readOnly: true 
      volumes:
      - name: nfs-volume # 일치해야함
        nfs:
          path: /var/nfs_storage
          server: 192.168.31.100 
    
# nfs 볼륨은 k8s에서 직접 연결하는 것 같지만
# 실제로는 호스트에서 연결이 되어있어야 한다.