apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  selector:
    matchLabels:
      volume: nfs-pv-volume # pv의 metadata의 labels
  resources:
    requests:
      storage: 1Gi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteMany # ReadWriteOnce, ReadWriteMany, ReadOnlyMany
